import type { Metadata } from 'next';
import { ogImageName, publicPage, type PublicPageId } from '@/config/public-pages';
import { site } from '@/config/site';
import { OG_LOCALE, routing, type Locale } from '@/i18n/routing';
import { localizedAlternates } from './alternates';

/** Size of the share images in public/og (generated by e2e/og-images.gen.ts). */
export const OG_IMAGE_SIZE = { width: 1200, height: 630 } as const;

/** Open Graph fields shared by every page. A page's openGraph replaces the layout's whole object. */
export function openGraphBase(locale: Locale) {
  return {
    type: 'website',
    siteName: site.name,
    locale: OG_LOCALE[locale],
    alternateLocale: routing.locales
      .filter((other) => other !== locale)
      .map((other) => OG_LOCALE[other]),
  } as const;
}

export function ogImageUrl(locale: Locale, id: PublicPageId): string {
  return `/og/${locale}/${ogImageName(id)}`;
}

/**
 * Metadata for a public page: title, description, canonical and hreflang links, and the page's
 * own share image in its language. `title` is null for the home page, which keeps the layout's
 * full title.
 */
export function publicPageMetadata({
  locale,
  id,
  title,
  description,
}: {
  locale: Locale;
  id: PublicPageId;
  title: string | null;
  description: string;
}): Metadata {
  const { path } = publicPage(id);
  const shareTitle = title === null ? `${site.name} | ${description}` : `${title} | ${site.name}`;
  const image = { url: ogImageUrl(locale, id), ...OG_IMAGE_SIZE, alt: shareTitle };
  return {
    ...(title === null ? {} : { title }),
    description,
    alternates: localizedAlternates(locale, path),
    openGraph: {
      ...openGraphBase(locale),
      url: `/${locale}${path}`,
      title: shareTitle,
      description,
      images: [image],
    },
    twitter: { card: 'summary_large_image', title: shareTitle, description, images: [image] },
  };
}
