/**
 * Phrase lists for the fixed rule checks (docs/SPEC.md §2), in Modern Standard Arabic, Levantine
 * and Algerian usage (Arabic script and common Latin spellings), English and French. They are
 * matched on folded text (text.ts), so letter variants and diacritics do not matter. The AI check
 * in M3c covers what a list cannot (D-103).
 */

/** R1: the customer is "everyone". */
export const EVERYONE = [
  'الجميع',
  'كل الناس',
  'جميع الناس',
  'كل شخص',
  'اي شخص',
  'اي حد',
  'اي حدا',
  'كل حدا',
  'كل العالم',
  'الكل',
  'كل الفئات',
  'جميع الفئات',
  'كل الاعمار',
  'جميع الاعمار',
  'قاع الناس',
  'ڨاع الناس',
  'ga3 nas',
  'ga3 ennas',
  'gaa nas',
  'tout le monde',
  'everyone',
  'everybody',
  'anyone',
  'anybody',
  'all people',
  'all ages',
] as const;

/** R2: "no competitors". */
export const NO_COMPETITORS = [
  'لا منافسين',
  'لا منافس',
  'لا يوجد منافس',
  'لا يوجد منافسين',
  'لا يوجد منافسون',
  'ليس لدي منافسين',
  'ما في منافس',
  'ما في منافسين',
  'مافي منافس',
  'ماكاش منافس',
  'ما كاين حتى منافس',
  'no competitors',
  'no competitor',
  'no competition',
  'pas de concurrent',
  'pas de concurrents',
  'aucun concurrent',
  'aucune concurrence',
] as const;

/** R2 on B4: "there is no solution today". "They put up with it" is an answer, not this. */
export const NO_ALTERNATIVE = [
  'لا يوجد حل',
  'لا حل',
  'لا توجد حلول',
  'ما في حل',
  'مافي حل',
  'ما كاين حتى حل',
  'ماكاش حل',
  'no solution',
  'no alternative',
  'there is no solution',
  'aucune solution',
  'pas de solution',
] as const;

/** R4: the founder wrote "I don't know" instead of choosing «لا أعرف». */
export const DONT_KNOW = [
  'لا اعرف',
  'لا ادري',
  'ما بعرف',
  'مش عارف',
  'ما اعرف',
  'مدري',
  'ما ادري',
  'ما نعرفش',
  'منعرفش',
  'ma na3rafch',
  'manarafch',
  'je sais pas',
  'je ne sais pas',
  'i don t know',
  'i dont know',
  'not sure',
  'no idea',
] as const;

/** R5: adjectives that need a number to mean anything. */
export const VAGUE = [
  'افضل',
  'الافضل',
  'احسن',
  'الاحسن',
  'اسرع',
  'ارخص',
  'اجود',
  'جوده عاليه',
  'اعلي جوده',
  'مميز',
  'مميزه',
  'فريد',
  'ممتاز',
  'اسهل',
  'اقوي',
  'better',
  'best',
  'faster',
  'cheaper',
  'high quality',
  'higher quality',
  'unique',
  'premium',
  'excellent',
  'easier',
  'mieux',
  'meilleur',
  'moins cher',
  'plus rapide',
  'qualite',
] as const;

/** R8: openings that describe a solution. */
export const SOLUTION_OPENINGS = [
  'تطبيق',
  'منصه',
  'موقع',
  'متجر',
  'خدمه',
  'سنقدم',
  'نقدم',
  'اقدم',
  'ساقدم',
  'مشروعي',
  'فكرتي',
  'منتجي',
  'app',
  'application',
  'platform',
  'website',
  'we will',
  'i will',
  'we offer',
  'i offer',
  'my product',
  'our product',
  'une application',
  'une plateforme',
] as const;

/** R8: words that show a problem is being described after all. */
export const PROBLEM_WORDS = [
  'يعاني',
  'يعانون',
  'تعاني',
  'مشكله',
  'مشاكل',
  'صعوبه',
  'صعب',
  'لا يستطيع',
  'لا يستطيعون',
  'يضطر',
  'يضطرون',
  'يضيع',
  'يخسر',
  'يخسرون',
  'مكلف',
  'غالي',
  'problem',
  'problems',
  'struggle',
  'struggles',
  'hard',
  'difficult',
  'can t',
  'cannot',
  'waste',
  'expensive',
  'costly',
  'pain',
  'probleme',
  'difficile',
] as const;

/** A3: "everything" instead of real skills. */
export const EVERYTHING = [
  'كل شيء',
  'كل شي',
  'كلشي',
  'كلش',
  'everything',
  'all of them',
  'tout',
] as const;

/** B8: "nobody can copy it". */
export const NOBODY_CAN = [
  'لا احد',
  'لا احد يستطيع',
  'ما حدا',
  'ما حدا بقدر',
  'محدش',
  'ما حد',
  'حتى واحد',
  'مستحيل',
  'no one',
  'nobody',
  'no one can',
  'impossible',
  'personne',
  'personne ne peut',
] as const;
